name: Completers Finish
favicon: null
layout_spectrum: 0.4683196237310767
typography_spectrum: 0.5063424280378968
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3424764112569392
  lightness: 0.06372184865176678
  saturation: 0.4639081417117268
  rhythmicContrast: 0.8205401953309774
purpose: []
